#[[config_calcul]]
#id_config_calcul = "SOLIVE_HAB"
#type_poutre = "Solive"
#usage = "PLANCHER_HAB"
#L_min_m = 2.0
#pas_longueur_m = 0.5
#pente_deg = 0.0
#entraxe_m = [0.4, 0.5, 0.6]
#classe_service = 1
#g_k_kNm2 = [0.5, 0.6, 0.7]
#q_k_kNm2 = 1.5
#categorie_q = "A"
#s_k_kNm2 = 0.0
#w_k_kNm2 = 0.0
#second_oeuvre = true
#double_flexion = false
#entraxe_antideversement_mm = 0

[[config_calcul]]
id_config_calcul = "PANNE_TOITURE_INACC"
type_poutre = "Panne"
usage = "TOITURE_INACC"
L_min_m = 2.0
pas_longueur_m = 0.5
pente_deg = [45]
entraxe_m = [1.2]
classe_service = 1
g_k_kNm2 = [0.4]
# g2_k_pcent = 0.0 non foncionel pour l'instant
q_k_kNm2 = 0.0
categorie_q = "H"
s_k_kNm2 = 0.36
w_k_kNm2 = 0.0
second_oeuvre = true
double_flexion = true
entraxe_antideversement_mm = 0
marge_securite = 0
#    [[filtre.regles]]
#    type = "liste"
#    champ = "classe_resistance"
#    valeurs = ["C24", "GL24H", "GT24"]