# =============================================================================
# configs_entre_vect.toml
# Configuration du mapage de l'ingestion de csv et du repertoire par defaut

# =============================================================================

#                                    WIP